const ADD_TO_BASKET = 'ADD_TO_BASKET';
const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
const CHANGE_QUANTITY_IN_BASKET = 'CHANGE_QUANTITY_IN_BASKET';
const RESET_BASKET = 'RESET_BASKET';

export default {
    ADD_TO_BASKET,
    REMOVE_FROM_BASKET,
    CHANGE_QUANTITY_IN_BASKET,
    RESET_BASKET
}